from pathlib import Path

ROOT_DIR = Path(__file__).parent
ROOT_FILE = ROOT_DIR / "files"
ARQUIVO_ICON = ROOT_FILE / "icon"

# Colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'

BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 22
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUM_WIDTH = 400